burichazuke/freemarket_sample_54a

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/database.yml
config/routes.rb

本番環境のセッティングのため（アセットコンパイル）に、pull requestを送ります。
この後、本番環境でrailsを起動します。

Taiki test

---

config/database.yml
config/routes.rb
config/unicorn.rb

本番環境用のユニコーンを作りました。
仮置きのrootは"items#index"です

create unicorn file

---

Gemfile

自分で追加したgemfileのコメントアウトを追加しました。

delete comment out

---

config/unicorn.rb

エンジンX導入のため、unicorn.rbのlisten部分を変更しました。

change listen for nginx

---

Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/environments/production.rb
config/unicorn.rb

create Capistrano files

---

config/deploy.rb

modify deploy.rb

---

Capfile
config/deploy.rb

modify capistrano

---

config/routes.rb

config/routes にマイページのルーティングに追加
マイページのルートをidに拠らないルートに設定するため

マイページのルーティングを追加

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/items/buy.scss
app/controllers/items_controller.rb
app/views/items/buy.html.haml

【マークアップ】商品購入確認ページ

---

app/controllers/application_controller.rb
config/deploy/production.rb

basic 認証の追加

---

app/assets/javascripts/brand-nav.js
app/assets/javascripts/category-nav.js
app/assets/stylesheets/config/_mixin.scss
app/assets/stylesheets/items/index.scss
app/assets/stylesheets/items/show.scss
app/views/items/_item.html.haml
app/views/items/new.html.haml
app/views/items/show.html.haml
app/views/layouts/application.html.haml
app/views/shared/_brand-nav.html.haml
app/views/shared/_category-nav.html.haml
app/views/shared/_header-nav.html.haml
app/views/shared/_header.html.haml
app/views/shared/_sell-btn.html.haml

・link_toのルーティング先の修正
・全体のa要素のカラーが青色になるCSSの修正
・ヘッダーのカテゴリーリストのdocument.readyが発火されないエラーの解決
・その他細かい修正
第一回スプリントレビュー突破のため！

スプリントレビュー前調整（鎌賀）

---

app/views/devise/registrations/credit_card.html.haml
app/views/items/_item.html.haml
app/views/items/_items2.html.haml
app/views/items/buy.html.haml
app/views/items/index.html.haml

イメージタグのファイルに拡張子をつけました
#Why
本番環境においてエラーが発生したため

イメージタグのファイル名変更

---

app/controllers/users/sessions_controller.rb
app/views/devise/sessions/new.html.haml
app/views/mypage/logout.html.haml
app/views/shared/_sidebar.html.haml

サインインとログアウトのページと機能を追加
ユーザーにログアウトと、サインインを簡単にできるようにするため

Make sign in and logout function

---

app/assets/stylesheets/items/buy.scss
app/assets/stylesheets/items/show.scss
app/views/items/buy.html.haml
app/views/items/show.html.haml

カードがない場合のエラー修正

---

app/views/items/show.html.haml

ビューファイルにuser_signed_in? &&　追記

---

app/views/mypage/index.html.haml

パンくずの表示位置でエラーが出ていたため修正
マイページにちゃんと飛べるように

パンくずの位置の修正

---

app/assets/stylesheets/items/buy.scss
app/controllers/items_controller.rb
app/views/items/done.html.haml
config/routes.rb

購入完了画面のビューを作成
ユーザーが購入を確認できるように

購入完了画面のビュー

---

app/assets/javascripts/favorite.js
app/controllers/comments_controller.rb

data-idを変更されると、違うitemにいいねされてしまうので修正しました

いいねのルーティングとjsの修正

---

app/views/items/_item-form.html.haml
app/views/shared/_search-side.html.haml

サーチのサイズと送料のバリューを変更
出品機能の変更による修正

サーチのサイズと送料を修正

---

app/assets/stylesheets/mypage/_index.scss
app/assets/stylesheets/mypage/_sidebar.scss
app/assets/stylesheets/users/_show.scss
app/controllers/mypage_controller.rb
app/views/mypage/index.html.haml
app/views/users/show.html.haml

マイページのサイドバーの修正

---

app/controllers/cards_controller.rb
app/views/cards/new.html.haml

カードの有効期限を２０年から登録するように
カード削除後のパスが間違っていたので修正
エラーのため

カード関係修正パス修正

---

app/assets/stylesheets/categories/_show.scss
app/views/categories/_cate-item.html.haml

- いいね数をcategory/showにて出力できるようにしました
- category/showのサイズ調整をしました。

サイズ調整・いいね数（カテゴリー）
